[package]
name = "among"
version = "1.0.0"
authors = ["Austin <atmatm6000@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gamemath = "0.4.0"
byteorder = "1.3.4"
enum-ordinalize = "3.1.8"
